templates_debugger/urls.py
from django.urls import path

from .views.dirs import DirsView
from .views.home import HomeView
from .views.render import RenderView

app_name = "templates_debugger"

urlpatterns = [
    path('', HomeView.as_view()),
    path('dirs/<path:path>', DirsView.as_view(), name='dirs'),
    path('render/<path:path>', RenderView.as_view(), name='render'),
]

templates_debugger/views/dirs.py
import os
import os.path

from django.apps import apps
from django.shortcuts import render
from django.views import View


class DirsView(View):
    def get(self, request, path: str, *args, **kwargs):
        parts = path.split("/")
        app = ".".join(parts[:-1])
        dir_name = parts[-1]
        app_config = next(filter(lambda c: c.name == app, apps.app_configs.values()))
        app_root = app_config.path
        template_dir = os.path.join(app_root, dir_name)

        template_list = []
        for base_dir, dirnames, filenames in os.walk(template_dir):
            for filename in filenames:
                template_list.append(os.path.join(base_dir, filename))

        return render(request, 'templates_debugger/dirs.html', context={
            'files': template_list
        })

templates_debugger/views/home.py
import fnmatch

from django.shortcuts import render
from django.template import Engine
from django.views import View

from ..settings import app_settings


class HomeView(View):
    def get(self, request, *args, **kwargs):
        engine = Engine.get_default()

        dirs = []
        for dir in engine.dirs:
            if fnmatch.fnmatch(dir, app_settings.MATCH_PATH):
                dirs.append(dir)

        return render(request, 'templates_debugger/index.html', context={
            'dirs': dirs
        })

templates_debugger/views/render.py
import os
import os.path

from django.shortcuts import render
from django.template.base import VariableNode
from django.template.loader import get_template
from django.template.loader_tags import IncludeNode
from django.views import View


class RenderView(View):
    def get(self, request, path: str, *args, **kwargs):
        template = get_template(path)
        variables = template.template.nodelist.get_nodes_by_type(VariableNode)
        includes = template.template.nodelist.get_nodes_by_type(IncludeNode)
        return render(request, path, context={
            'templates_debugger_enabled': True
        })

templates_debugger/templates/templates_debugger/dirs.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_urls %}


{% block content %}
    {{ block.super }}

    <ul>
        {% for file in files %}
            <li><a href="{% url 'templates_debugger:render' path=file%}">{{ file }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

templates_debugger/templates/templates_debugger/index.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_urls %}


{% block content %}
    {{ block.super }}

    <ul>
        {% for dir in dirs %}
            <li><a href="{% url 'templates_debugger:dirs' path=dir%}">{{ dir }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}